import {
  CalendarBlank,
  MagnifyingGlass,
  Gear,
  SunHorizon,
  Moon,
  Note,
  ClockCountdown,
  ArrowsClockwise,
  ShoppingCart,
  ArrowCounterClockwise,
  Trash,
  ChartBar,
  Tag,
  Bell,
  Palette,
  LinkSimple,
  Star,
  Question,
  CaretRight,
  CaretLeft,
  CaretDown,
  Clock,
  PushPin,
  SmileySad,
  Sparkle,
  CheckSquare,
  ForkKnife,
  Broom,
  Briefcase,
  Car,
  Coffee,
  MusicNote,
  Book,
  Barbell,
  Heart,
  Phone,
  House,
  GraduationCap,
  Wallet,
  GameController,
  Camera,
  Plus,
  WashingMachine,
  CookingPot,
  PawPrint,
  Pill,
  FirstAidKit,
  Receipt,
  Article,
  Envelope,
  Users,
  Train,
  Gift,
  Scissors,
  PersonSimpleRun,
  PersonSimpleTaiChi,
  Bicycle,
  PencilSimple,
  Funnel,
  Guitar,
  Basketball,
  SoccerBall,
  Volleyball,
  PaintBrush,
  Rocket,
  Cat,
  Dog,
  Bird,
  Fish,
  Rabbit,
  Flower,
  Tree,
  Sun,
  Airplane,
  Bus,
  Sailboat,
  Backpack,
  Suitcase,
  MapPin,
  Tent,
  Campfire,
  Cake,
  Pizza,
  Bathtub,
  Bed,
  CreditCard,
  PiggyBank,
  Lock,
} from '@phosphor-icons/react';

type PhosphorComp = React.ComponentType<{
  weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';
  size?: number | string;
  className?: string;
  color?: string;
}>;

type P = { size?: number; className?: string };

const make = (Ic: PhosphorComp, defaultSize = 20) => {
  function PhosphorIcon({ size = defaultSize, className }: P) {
    return <Ic weight="bold" size={size} className={className} />;
  }
  return PhosphorIcon;
};

export const AppIcons = {
  calendar:  make(CalendarBlank),
  search:    make(MagnifyingGlass),
  settings:  make(Gear),
  wake:      make(SunHorizon, 18),
  sleep:     make(Moon, 18),
  task:      make(Note, 18),
  freeTime:  make(ClockCountdown, 12),
  repeat:    make(ArrowsClockwise, 12),
  shopping:  make(ShoppingCart, 40),
  postponed: make(ArrowCounterClockwise, 12),
  trash:     make(Trash, 28),
  stats:     make(ChartBar, 18),
  tag:       make(Tag, 18),
  bell:      make(Bell, 18),
  palette:   make(Palette, 18),
  link:      make(LinkSimple, 18),
  star:      make(Star, 18),
  question:  make(Question, 18),
  caretRight: make(CaretRight, 18),
  caretLeft:  make(CaretLeft, 18),
  caretDown:   make(CaretDown, 14),
  clock:       make(Clock, 18),
  pin:         make(PushPin, 18),
  smileySad:   make(SmileySad, 40),
  sparkle:     make(Sparkle, 40),
  checkSquare: make(CheckSquare, 12),
  food:       make(ForkKnife, 18),
  clean:      make(Broom, 18),
  work:       make(Briefcase, 18),
  travel:     make(Car, 18),
  rest:       make(Coffee, 18),
  music:      make(MusicNote, 18),
  book:       make(Book, 18),
  exercise:   make(Barbell, 18),
  health:     make(Heart, 18),
  phone:      make(Phone, 18),
  home:       make(House, 18),
  study:      make(GraduationCap, 18),
  money:      make(Wallet, 18),
  game:       make(GameController, 18),
  camera:     make(Camera, 18),
  plus:       make(Plus, 28),
  running:    make(PersonSimpleRun, 18),
  yoga:       make(PersonSimpleTaiChi, 18),
  bicycle:    make(Bicycle, 18),
  washing:    make(WashingMachine, 18),
  cooking:    make(CookingPot, 18),
  paw:        make(PawPrint, 18),
  medicine:   make(Pill, 18),
  hospital:   make(FirstAidKit, 18),
  payment:    make(Receipt, 18),
  document:   make(Article, 18),
  mail:       make(Envelope, 18),
  meeting:    make(Users, 18),
  train:      make(Train, 18),
  gift:       make(Gift, 18),
  scissors:   make(Scissors, 18),
  pencil:     make(PencilSimple, 18),
  filter:     make(Funnel, 18),
  guitar:     make(Guitar, 18),
  basketball: make(Basketball, 18),
  soccer:     make(SoccerBall, 18),
  volleyball: make(Volleyball, 18),
  paint:      make(PaintBrush, 18),
  rocket:     make(Rocket, 18),
  cat:        make(Cat, 18),
  dog:        make(Dog, 18),
  bird:       make(Bird, 18),
  fish:       make(Fish, 18),
  rabbit:     make(Rabbit, 18),
  flower:     make(Flower, 18),
  tree:       make(Tree, 18),
  sun:        make(Sun, 18),
  airplane:   make(Airplane, 18),
  bus:        make(Bus, 18),
  boat:       make(Sailboat, 18),
  backpack:   make(Backpack, 18),
  suitcase:   make(Suitcase, 18),
  location:   make(MapPin, 18),
  tent:       make(Tent, 18),
  campfire:   make(Campfire, 18),
  cake:       make(Cake, 18),
  pizza:      make(Pizza, 18),
  bathtub:    make(Bathtub, 18),
  bed:        make(Bed, 18),
  creditcard: make(CreditCard, 18),
  piggybank:  make(PiggyBank, 18),
  lock:       make(Lock, 18),
};
